name = "cf-worker-images"
main = "src/index.ts"
compatibility_date = "2023-02-20"

[vars]
ORIGIN = "plicnik.com"
WORKER_HOST = "cf-worker-images.melle-nieling.workers.dev"
CLOUDINARY_CLOUD = "dfogyuw5e"
